### ISSUE TITLE
Enable regular expressions in --filter

### ISSUE THREAD

**Issue by jscotka** [psss/fmf#35]
fmf has inconsistency of behavior of `--name` and `--filter` options and also function insides:
example `--name a --name b` means logical **OR**
although using more `--filter` statements means logical **AND**
and also it is very hard to write **NOT** statement (possible to write via regexp: `'^(?!.*inverse_match).*'`) and logical AND via name filter like `--name '^((?!.*value1)|(?!.*value2)).*'`

### possible solution
would be good to copy `name` -> `data["name"]` then I will be able to use filter expressions as for other elements via `--filter` . But this lead to side effect that user cannot define "name" item. and also not easy to understand if `name` is just  this item name or whole *path* name like `/a/b/c` and then how to deal with items.

and also   there is another issue is that `--filter` function does not allow to use some asterisk patters like: `tags: Tier*` to match everything, what will be important to filter names because it is not easy to filter it via full path.

What do you think, is there some simple solution to do this or we do not plan to change this behaior.
Actual solution is fine, but little bit mixing two concepts together and two types of logical statements.

BTW it is close to relevancy. Relevancy syntax should provide these item types for filters.

**Comment by psss** [comment]
Thanks for describing the issues, Honzo. My main impression of what you described is that you expect a very extended functionality from the command line tool. The initial idea was to have it just for quick inspection of the metadata. I'm ok with adding some more useful features but I expect that for production use Python API will be used instead which provides much better flexibility. I believe you can very easily implement all of the use cases mentioned above directly from Python. But let's look for the command line:

Different AND/OR logic for options is intentional and based on common use cases: Selecting node by identifier using `--name` should easily support choosing two objects rather then complex AND logic. The `--filter` on the other hand supports OR in the syntax. I also chose this default to be consistent with how `wow` handles advanced filters. But perhaps we could default for OR here as well. Do you think it would be a better choice?

Adding `name` to filter could be an option, but we would have to introduce some unique / reserved prefix (like fmf) not to block using attribute of the same name. I'm still not quite sure about that. I makes also sense to keep the `data` dict clean.

It makes sense to allow regular expressions in filter. I'll update the `prune()` method accordingly.

**Comment by AloisMahdal** [comment]
FWIW...

IMO the filtering being OR by default would be confusing; most filters I can think of act as AND by default.

`--name` seems natural being OR because things naturally don't have multiple names; (OTOH it being actually regex makes it kinda like `--filter`.)
